my_string = input("Напишите что-нибудь: ")
print("Вы ввели ", len(my_string), " символов")
print("Вот Ваш текст в верхнем регистре: ", my_string.upper())
print("Вот Ваш текст в нижнем регистре: ", my_string.lower())
print("Мы подчистили пробелы в Вашем тексте: ", my_string.replace(" ", ""))
print("Первый символ Вашего текста: ", my_string[0])
print("Последний символ Вашего текста: ", my_string[-1])
